root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - '@vue/typescript/recommended'
  - '@vue/prettier/@typescript-eslint'
  - '@vue/prettier'
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - graphql
  - '@typescript-eslint'
ignorePatterns:
  - node_modules/*
  - src/generated/*
  - dist/*
  - .vscode/*
  - tailwind.config.js
rules:
  '@typescript-eslint/no-unused-vars':
    - 1
    - args: none
      argsIgnorePattern: _
      varsIgnorePattern: _
